### ISSUE TITLE
Can I specify location for Downloads and Exploded folders?

### ISSUE THREAD

**Issue by dneto0** [google/cdep#21]
I noticed cdep places downloads and exploded files in $HOME/.cdep

I'd like to keep build trees independent of each other.   Can I control where those folders go?
I'm concerned about races between builds, and also about ease of space management.

**Comment by jomof** [comment]
My plan is to add a field in cdep.yml like:

   home: build/cdep-downloads

I'll work on that now, it shouldn't take too long.

Regarding race, I thought I had covered that but I see now that I didn't fully. I'm opening a second issue to cover that.

**Comment by jomof** [comment]
I've added the field I mentioned to cdep.yml. Documented here https://github.com/google/cdep/blob/master/doc/cdep-yml.md
