### ISSUE TITLE
Mode to resolve dependencies on demand, and do nothing else?

### ISSUE THREAD

**Issue by dneto0** [google/cdep#5]
I might have misunderstood the usage model.   But it looks like cdep wants to download components during a build: 
- the "main cdep executable", downloaded by the boostrapping jar file
- the referenced package dependencies.

I really don't want a build system to update its source tree during a build.  Is there a mode for using cdep where it *just* resolves package dependencies?  Then at least I can segregate that step into a stage before  actually building a project.

**Comment by jomof** [comment]
Hi David, you can run ./cdep redownload. This will resolve everything then download and unzip all archives. Is that what the kind of resolve you're looking for?

**Comment by dneto0** [comment]
That sounds like it does what I want.  May I suggest it be available as "cdep download"  ?  :-)
It would be really nice if the usage doc called out this mode.
