### ISSUE TITLE
Can cdep be used with regular Cmake (not Android Studio CMake)?

### ISSUE THREAD

**Issue by dneto0** [google/cdep#6]
I couldn't tell from the usage docs.

**Comment by DanAlbert** [comment]
Yes, though we should probably state this more explicitly.

**Comment by jomof** [comment]
Yes, the generated CDep glue will detect whether it is the Android Studio CMake or CMake 3.7.1+ (which is the first version with built-in Android support)

**Comment by jomof** [comment]
I should add that most of the packages I wrote are built with vanilla CMake so that code path is heavily tested.
