### ISSUE TITLE
CMAKE_SYSTEM_VERSION is 24

### ISSUE THREAD

**Issue by ggfan** [google/cdep#68]
looking at this [issue](https://github.com/googlesamples/android-vulkan-tutorials/issues/50)
The error is:
```
CMake Error at /Users/gfan/proj/android-vulkan-tutorials/tutorial06_texture/.cdep/modules/cdep-dependencies-config.cmake:169 (message):
    Android runtime '' is not supported by com.github.ggfan:shaderc:0.0.1.
    Supported: gnustl c++
```
This is due to the following:
```
  if(NOT CMAKE_SYSTEM_VERSION EQUAL 1)
    set(cdep_determined_android_runtime ${CMAKE_ANDROID_STL_TYPE})
    set(cdep_determined_android_abi ${CMAKE_ANDROID_ARCH_ABI})
    set(cdep_determined_android_platform_level ${CMAKE_SYSTEM_VERSION})
  else()
    set(cdep_determined_android_runtime ${ANDROID_STL})
    set(cdep_determined_android_abi ${ANDROID_ABI})
    set(cdep_determined_android_platform_level ${ANDROID_PLATFORM_LEVEL})
    set(cdep_supports_compiler_features FALSE)
  endif()
```
CMAKE_SYSTEM_VERSION is 24 ( target_sdk_version), and CMAKE_ANDROID_STL_TYPE is nothing. 

how to fix it?  thanks!

**Comment by gpx1000** [comment]
Hi Greg,

I put a bit of a workaround for this bug in the last PR.  https://github.com/google/cdep/issues/60 it's the same issue as there.
What I'm doing locally is to set ANDROID_SYSTEM_VERSION to be what CMAKE_SYSTEM_VERSION should be.  The intention is setting ANDROID_SYSTEM_VERSION occurs in the toolchain file so this is automatically fixed.  Until it's in a future shipped with ndk toolchain file, I've been doing it in my local toolchain file; however, it's equally workable to just set it in any CMakeLists.txt file.
I seem to remember @jomof mentioning something about CMAKE_SYSTEM_VERSION creates clashes if there's a system cmake yet the android cmake is being used?  But, Jomo will know this better than me.
In any case, you can either hardcode the version to be the cmake variable ANDROID_SYSTEM_VERSION or CMAKE_SYSTEM_VERSION and it should work.

**Comment by jomof** [comment]
I'm looking at this now to refresh my memory

**Comment by ggfan** [comment]
Yeah it is the hardcoded hack of my own CMAKE_SYSTEM_VERSION causing the trouble. it is fixed. Thank you so much!
