### ISSUE TITLE
cdep overwrites itself if run on the same directory it was cloned in

### ISSUE THREAD

**Issue by sivu** [google/cdep#9]
running git clone https://github.com/jomof/cdep-redist.git  and then running cdep wrapper on that directory makes cdep unusable since it overwrites itself with zero byte files

**Comment by jomof** [comment]
I think the repro steps are these:
 git clone https://github.com/jomof/cdep-redist.git 
 ./cdep wrapper
Can you confirm?

**Comment by sivu** [comment]
Those are the exact steps. That results in zero size cdep and cdep.bat

**Comment by jomof** [comment]
Thanks, I made it an error
